backend/controllers/CouponController.php
<?php
/**
 * Created by PhpStorm.
 * User: Planess group
 * Date: 21.02.2017
 * Time: 0:20
 */

namespace backend\controllers;


use yii\web\Controller;

class CouponController extends Controller {

    public function actionIndex(){
        return $this->render('index');
    }
}

backend/controllers/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: Planess group
 * Date: 21.02.2017
 * Time: 0:29
 */

namespace backend\controllers;


use yii\web\Controller;

class ProductController extends Controller {

    public function actionIndex(){


        return $this->render('index');
    }

}

backend/controllers/RewardController.php
<?php
/**
 * Created by PhpStorm.
 * User: Planess group
 * Date: 20.02.2017
 * Time: 22:16
 */

namespace backend\controllers;


use common\models\User;
use yii\data\ActiveDataProvider;
use yii\web\Controller;

class RewardController extends Controller {

    public function actionIndex(){
        $query = User::find();

        $bestSeller = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' =>20,
            ],
            'sort' => [

            ],
        ]);

        $activeParticipant = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
            ],
            'sort' => [],
        ]);

        $fromTeam = new ActiveDataProvider([
            'query' => $query->where(['reward_team'=>1]),
            'pagination'=>[
                'pageSize' => 20,
            ],
            'sort'=>[],
        ]);

        return $this->render('index',[
            'bestSeller'=>$bestSeller,
            'activeParticipant' =>$activeParticipant,
            'fromTeam'=>$fromTeam,
        ]);
    }
}

backend/controllers/UsersController.php
<?php
/**
 * Created by PhpStorm.
 * User: Planess group
 * Date: 20.02.2017
 * Time: 0:29
 */

namespace backend\controllers;


use backend\models\RegisterForm;
use common\models\User;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;

class UsersController extends Controller {
    public function actionAll() {
        $users = new ActiveDataProvider([
            'query'      => User::find()->select(['id', 'username','email'])->asArray(),
            'sort'       => false,
            'pagination' => [
                'pageSize' => 40,
            ],
            'key' => 'id',
        ]);

        return $this->render('all', [
            'dataProvider' => $users,
        ]);
    }

    public function actionRoles() {
//        $roles = (new Query())->from('{{%auth_item}}')->where(['type' => 1])->all();

        return $this->render('roles', [
//            'roles' => ArrayHelper::map($roles, 'name', 'name'),
        ]);
    }

    public function actionUpdateUser($id = null) {
        $model = new RegisterForm();
        if (!is_null($id)) {
            $id = intval($id);
            $user = User::findOne($id);
            if (is_null($user)) throw new BadRequestHttpException("Invalid user id $id");

            $model->attributes = $user->attributes;
        }

        $request = \Yii::$app->request;
        if ($request->isPost && $model->load($request->post())) {
            if ($model->validate()) {
                $model->save(false);

                return $this->redirect(['all']);
            }
        }

        return $this->render('update-user', [
            'model' => $model,
        ]);
    }
}

backend/views/layouts/basic.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>

        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Wearent <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php

use yii\widgets\Menu;
use yii\widgets\Pjax;

/* @var $this \yii\web\View */
/* @var $content string */

\backend\assets\AngularAsset::register($this);
?>

<?php $this->beginContent('@app/views/layouts/basic.php'); ?>

<div class="row">
    <div class="col-sm-3" id="backend-sidebar">
        <?= Menu::widget([
            'items' => [
                [
                    'label' => 'Пользователи',
                    'items' => [
                        ['label' => 'Список', 'url' => ['/users/all']],
                        ['label' => 'Доступы', 'url' => ['/users/roles']],
                    ],
                ],
                [
                    'label' => 'Награды',
                    'url'   => ['/reward/index'],
                ],
                [
                    'label' => 'Купоны',
                    'url'   => ['/coupon/index'],
                ],
                [
                    'label' => 'Категории/Товары',
                    'url' => ['/product/index'],
                ],
            ],
        ]); ?>
    </div>
    <div class="col-sm-9">
        <!--        --><?php //Pjax::begin([
        //            'id'           => 'content-backend-pjax',
        //            'linkSelector' => '#backend-sidebar a',
        //            'timeout'      => 3000,
        //        ]); ?>
        <?= $content; ?>
        <!--        --><?php //Pjax::end(); ?>
    </div>
</div>

<?php $this->endContent(); ?>