backend/models/RegisterForm.php
<?php
/**
 * Created by PhpStorm.
 * User: Planess group
 * Date: 20.02.2017
 * Time: 14:27
 */

namespace backend\models;


use common\models\User;
use yii\base\Model;

class RegisterForm extends Model {

    const SEX_MALE   = 1; // мужсткой пол
    const SEX_FEMALE = 2; // женский пол

    public $id;
    public $username;
    public $first_name;
    public $last_name;
    public $sex;
    public $about_me;
    public $birthday;
    public $country;
    public $city;
    public $email;

    public function rules() {
        return [
            ['id', 'integer', 'min' => 0],
            [['first_name', 'last_name', 'username', 'about_me'], 'trim'],
            [['first_name', 'last_name', 'username', 'about_me'], 'string'],
            [['username', 'email'], 'required'],
            ['email','email'],
            ['sex', 'integer'],
            ['sex', 'in', 'range' => [self::SEX_MALE, self::SEX_FEMALE]],
            ['birthday', 'date'],
        ];
    }


    public function attributeLabels() {
        return [
            'first_name' => \Yii::t('app', 'First name'),
            'last_name'  => \Yii::t('app', 'Last name'),
            'sex'        => \Yii::t('app', 'Sex'),
            'about_me'   => \Yii::t('app', 'About me'),
        ];
    }

    public function getSexTags() {
        return [self::SEX_MALE => \Yii::t('app', 'Male'), self::SEX_FEMALE => \Yii::t('app', 'Female')];
    }

    public function save($validate = true) {
        if ($validate && !$this->validate()) {
            return false;
        }

        $id = intval($this->id);
        if ($id > 0) {
            $u = User::findOne(['id'=>$id]);
        } else {
            $u = new User();
            $u->setPassword(\Yii::$app->security->generateRandomString(12));
        }
        if (is_null($u)) return false;

        $u->attributes = $this->attributes;
//        print_r($u);
//$u->save();print_r($u->errors);exit;
        return $u->save();
    }
}

common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string  $username
 * @property string  $password_hash
 * @property string  $password_reset_token
 * @property string  $email
 * @property string  $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string  $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface {
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE  = 10;


    /**
     * @inheritdoc
     */
    public static function tableName() {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id) {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null) {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     *
     * @return static|null
     */
    public static function findByUsername($username) {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     *
     * @return static|null
     */
    public static function findByPasswordResetToken($token) {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status'               => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     *
     * @return bool
     */
    public static function isPasswordResetTokenValid($token) {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int)substr($token, strrpos($token, '_') + 1);
        $expire    = Yii::$app->params['user.passwordResetTokenExpire'];

        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['username'], 'trim'],
            [['username'], 'required'],
            ['username', 'string', 'max' => 65],
            ['email', 'email'],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getId() {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey) {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey() {
        return $this->auth_key;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     *
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password) {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password) {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey() {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken() {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken() {
        $this->password_reset_token = null;
    }
}

backend/controllers/UsersController.php
<?php
/**
 * Created by PhpStorm.
 * User: Planess group
 * Date: 20.02.2017
 * Time: 0:29
 */

namespace backend\controllers;


use backend\models\RegisterForm;
use common\models\User;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;

class UsersController extends Controller {
    public function actionAll() {
        $users = new ActiveDataProvider([
            'query'      => User::find()->select(['id', 'username','email'])->asArray(),
            'sort'       => false,
            'pagination' => [
                'pageSize' => 40,
            ],
            'key' => 'id',
        ]);

        return $this->render('all', [
            'dataProvider' => $users,
        ]);
    }

    public function actionRoles() {
//        $roles = (new Query())->from('{{%auth_item}}')->where(['type' => 1])->all();

        return $this->render('roles', [
//            'roles' => ArrayHelper::map($roles, 'name', 'name'),
        ]);
    }

    public function actionUpdateUser($id = null) {
        $model = new RegisterForm();
        if (!is_null($id)) {
            $id = intval($id);
            $user = User::findOne($id);
            if (is_null($user)) throw new BadRequestHttpException("Invalid user id $id");

            $model->attributes = $user->attributes;
        }

        $request = \Yii::$app->request;
        if ($request->isPost && $model->load($request->post())) {
            if ($model->validate()) {
                $model->save(false);

                return $this->redirect(['all']);
            }
        }

        return $this->render('update-user', [
            'model' => $model,
        ]);
    }
}

backend/views/users/all.php
<?php
/**
 * Created by PhpStorm.
 * User: Planess group
 * Date: 20.02.2017
 * Time: 0:30
 */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/** @var \yii\web\View $this */
/** @var \yii\data\ActiveDataProvider $dataProvider */
?>

<div class="row">
    <div class="col-sm-12">
        <?= Html::a('New user', ['/users/update-user'], ['class' => 'btn btn-primary']); ?>
    </div>
    <div class="col-sm-12">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns'      => [
                'id',
                'username',
                'email:text',
                [
                    'class'      => \yii\grid\ActionColumn::className(),
                    'template' => '{update}',
                    'urlCreator' => function($action, $model, $key, $index) {
                                    return Url::to(["$action-user", 'id' => $key]);
                    },
                ],
            ],
        ]); ?>
    </div>
</div>

backend/views/users/roles.php
<?php
/**
 * Created by PhpStorm.
 * User: Planess group
 * Date: 20.02.2017
 * Time: 0:30
 */

use yii\helpers\Html;

/** @var \yii\web\View $this */
?>

roles

backend/views/users/update-user.php
<?php
/**
 * Created by PhpStorm.
 * User: Planess group
 * Date: 20.02.2017
 * Time: 14:33
 */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use kartik\daterange\DateRangePicker;

/** @var \yii\web\View $this */
/** @var \backend\models\RegisterForm $model */

?>

<?= Html::a('back', ['/users/all']); ?>

<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'username')->textInput(); ?>
<?= $form->field($model, 'first_name')->textInput(); ?>
<?= $form->field($model, 'last_name')->textInput(); ?>

<?= $form->field($model, 'sex')->dropDownList($model->sexTags, ['prompt' => \Yii::t('app', 'Choose') . '...']); ?>
<?= $form->field($model, 'about_me')->textarea(['rows' => 4]); ?>

<?= $form->field($model, 'birthday')->widget(DateRangePicker::className()); ?>

<?= $form->field($model, 'email')->textInput(); ?>
<?= Html::submitButton('Save'); ?>

<?php ActiveForm::end(); ?>